* 『賢女のパン』うちなーぐち訳
* Page 1
soo?iri'winagu tu paN nu hanasi
(0・ヘンリー短編集「賢女のパン」より)
原 作: O Henry .
沖縄語訳: 浜崎盛久
* Page 2
?wiitaci 'winagu miQcaN ga macinu kadu nakai paNnu macijagwaa sootaNdi.
(?isikizai miici nubuti hasiru ?akiinee ciriN ciriNQsi ?eezinu nairu gutu natooru macija jataN.)
miQcaNoo kutusi siNzuu(40). zinkoo Nkai 40maN'eN nu ziN azikiirusakunu kumasiimuN jataN.
jununakaNkaija miQcaN jaka naahwin niibiciNkai 'iN nu neeN cu jatiN jaamuQcooru cu nu rateeN 'uN.
1 shuukann ni takeN mikeeN kimati macijaNkai cuuru cuinu cakunu 'utaN.
miQcaNoo ?unu cakuNkai nuugajara cimugakai hazimataN.
?aNsukaa wakakuN neeran 'ikiga jasiga, gaNcoo kakiti hwizee tiiniini sutee ?asiga sacee tugaraceetaN ?unu'ikigaa sacisima kutuba sutaN, cicooru joohukoo ?amakuma jariti kuusaQti, jariraN tukuroo wabuwabu
* Page 3
sootaN.
jasiga caa ciriinigwaaQsi riizisahuuN natootaN ?unuQcoo caa kuhwatooru hurupaN nu katamai taaci kooti ?icutaN.
mii paNoo tiici 5jeN jasiga kufwatooru hurupanoo taaciQsi 5jeN jataN.
?unu ikigaa caa kuhwa paN jaka hukanee koo'irukutoo neeNtaN.
?arutuci miQeaNoo ?unu ikiga nu ?iibiNkai ?akaa tu caa ?iruu nu sun nu cicoosi mii ?atitaN
?unutuci kara miQcaNoo unu 'ikigaa 'iikaci jasiga jukainee hwiNsuumuN jaraNdi duukuru ?umiiQsi neeraN nataN.
maagana nu jaanu ?iricanuhwicaNkai simatooti
?uma'uti 'iikaciganaa kuhwa paN kadi miQcaN macijanu
maasagisaru paN nu kutu kaNgeetai soorahazi jaQsaa.
miQcaNoo ?aci îaciitu sooru beekoN tu zamu nu cicooru
hukuhuku dikiticaakinu roorupaN tu ?uca meenacooti
iisuNkai 'ici ?uhu ?iici seesiisiiQsi, ?anu hwiNsuu
* Page 4
'iikaci ga hwiisa kazi nu ?iQcicuuru ?iricanuhwica 'uti kuhwatooru huru panuNdeeN kamaNgutu waNtu mazuuN maasamuN kaditurasee simurumuNnu Ndi tumuiru kutunu juu ?ataN.
kisaN ?icaru tuui miQca Noo sinasakimucinu 'inagu jataN.
?aNcuga sikuci nu waa kaNgeega ?atatiga'ura tamisiQsi NnrawaruNci ?arutuci miQca Noo ?aQcigacii micibataNzi kooticaru tiicinu 'ii,
duunu zaagwaa kara muci ?Nzaci ?uri macijanu miidacuru tukurunu tanaNkai tatiti lucaN.
?uree Benisu nu cura ciici nu 'ii jataN. turabaaciN nu ?uhu gusiku (Nci 'iiNkaija kakaQtootaN) jasiga.
hukanee tiNtu kumutu goNdora nu kakaQti, irunu curasaja miimaQteeN nairusaku jati 'iikaci jaree ciQtu cinicicura hazi.
* Page 5

hucikabikeeN ?atuni ?anu cakunu caN.
「guburii jasiga hurupaN taaci kooibira」
「cura 'ii nu ?aibiisa jaa」
miQcaNga paN cicidooini ?anuQcuga icaN.
「?aN ?umaarijabiimi tai」
miQcaNoo dikacaN dici 「waaga sicusee 'ii tu ?urikara.....」
(matijoo kaNsi hwee beetu「'iikaci」 nuunu ndi icee naraN)
「?urikara 'ii jaibiiN」 ci bicinu kutubaNkai keeti.
「kuree makutuni jutasaru 'ii jaNdi ?umaarijabiiga jaa?」
「gusiku ja」 ndi cakoo ?ijaani 「?ansukaa ?aibiraN
enkinhou nu kacikatanu macigatooibiiN guburii sabira」
?unuQcoo paN ?ukituQti gumaguriigwaaQsi soosootu ?Nziti ?NzaN.
jasa ?anuQcoo tasikani 'iikaci jaN. miQcaNoo Qunu'ii
* Page 6
duunu zaagwaaNkai muduci ?ucaN.
?anuQeu ga mii ja gaNcoonu Quukunakai curazimu muQcooru cuNci waka'iN, ?anuQcu nu hwirusaru!.
hwicee ja ?aNsi cumi 'Ncaru dakiQsi enkinhou nu kacikataN wakajui ?unu ?wiini hurupaN kadooti kuracooNdi.
jasiga sugurimuNdi ?jusee sikiNkara mitumirariiru made kucisa ?umiiN saNtoo naraN.
musika ?unu sugurimuN ziNkooNkai ?azikiteeru
40maN'eN tu kunupaN macija tu waN cimugukuru tu
saani kasii ja naraNga ara. 'ii nu kacikata nu
taminiN caQsa 'iikutuga jara Ndi ?umaariisiga
jasiga miQcaN jo ?uree ?imi munu gatai du jaru
cicaguroo ?unu Qcoo macija Nkai meNseeru kaazi
paN dana nu
?amatu kumatu taNkaanaaQsi
* Page 7
?iQtuci sikiNbanasiiQsi keeitaN.
?unuQcoo miQcaN juNtaku cini ?iQcooNnee sutaN.
?aNsikara caanugutu hurupaN bikeeN kooti ?icutaN.
keekin paiN miQcaNga cukuteeru mizirasii sariiraN di ?juru maasa kwaasiN nuutiiciN kootee ikaNtaN ?uNcuga sideeni joogariti kuNcinu neeNnati cooNneeQsi masaanee miijutaN.
?uNcuga hwiNsuuraasaru kooimunun kai nuugana maasamuN siibuNsi ?usagirana Ndee ?umueesutiN nuugajara ?izigwaanu ?NziraN.
?uNcuNkai hazi kakasuru kutoo seenaraN di tumutaN.
'iikacinu cunucaaja buN mucinu îuhusaNdi ?jsee
miQcaNuN wakati'utagutu.
miQcaNoo macija Nkai ?Nziinee mizitama muyoo nu
?iicunu nu burausu ciirugutu natooN.
* Page 8
?uukunu zaaNzee MARUMERO nu mii tu HOOSJA tuQsi
Žihuuna maNkimuN cukutaN.
duuiru ?NzasuNdi kaNneeru muN cikairu cunu 'uNdinu hanasi jaN.
?arutuci ?anu cakunu macijaNkai caani hurupaN
koo'iNdi tananu 'wiiNkai 5jeN nu miihugaa ziN ?ucikitaN.
miQcaNga hurupanuNkai tii nubasaNdi saru tucini BuuBuu zaNzaNQsi magi ?utu tatiti SHOOBOO nu tuuti
ficutaN. cakunucaa ja 'Nna ?isuzi hasiruguciiNkai Nnziga
?icutaN.
miQca Noo ?attani ?ihuuna kaNgee ?umiitaQci
namajasaNdi tumutaN. macijanu tananu icibaN
sicaNkai namasaci ciiciijaa ga uci ?Njaru BATAAga rateeN ?aN.
miQcaNoo paNciri NAIFU Qsi taacinu huru panuNkai cirikata ?iQti ?ununakaNkai BATAA ?uhu ?uhuutu
* Page 9
?usikudi paN mutuduuiNkai nooci fucaN. cakunu muduti carutucinee miQca Noo paN cicidootaN. cakunucaaga ?icijakan sikiNbanasiQsi keeti ?Nzagutu miQca Noo nakara ?uQsaa ?asiga tuhwee cimugakaiN
?ata N. duku ?izibuuta siizuukoo neeNtagajaa?
?aNcuga cimu jaNtee neeraN gajaa?
?araN ?uNgutooru kutoo neeN.
「hana kutuba」 'Ndi ?jusee ?asiga 「kweemun kutuba」 nuunuNcee nee Nhazi deemuN. BATAA ga inaguraasiku neeN nusikaimuN di ?jariiru wakee neeNhazi deemuNnu ?unuhwiija ?icimadin ?unukutu bikeen kangeetootaN.
miQcaNnu ?unu guma tiNcama, ?aNcuga miiatiiru tucinu sigata kaNgeeti 'NcaN.
?uNcoo ?ii kacuru hudi tu PARETTO 'hwicaNkai ?ucurahazi caNtu kacaru ENKINHOU Nkai cimuhuzi jagati subinairu
* Page 10
iinu umaNkai taQcoorahazi.
?a Ncoo boroboro nu hurupaN tu mizituQsi
?asabaN nu sikooi surahazi ?aNsikara paN ciraNdi
surahazi
?aNsagutu ?aaaa miQcaNoo ?akaziraa nataN.
?aNcoo ?unupaN kamuru baani ?umaNkai BATAA
?iQtaru tiinukutu kaNgeeti turasigasura?
?urikara
macijanu ?iriguciinu ?eezinu ?utunu ihuuna naijooQsi
taaganaga magi ?ututatiti ?iQcicuutaN
miQcaNga ?isuzi macija Nkai ?Nziti ?Nzagutu
tainu 'ikiganu ?NmaNkai taQcootaN
cuija paipu kuutooru waka 'ikigaa... (kuree namamadee
'Ncarukutunu neeN ikiga.. naacuija miQcaNga ?iiru
?anu 'iikaci.
* Page 11
iikacee ?akaziraa nati boosee joogaa kaNziQsi cuburoo
kaNtaamoojaaQsi taacinu tiizikuN cuuzuutu niziti.
?uri miQcaN 'Nkati huimiguracootaN.
?ikananuujatiN miQcaN 'Nkati jataN.
「bakamuN!」 ?uNcoo sitatakanu ?uhugwiiQsi ?abiitubacaN
cizikiti 「soonugaa」 'Ndigara Eema kutubaQsi ?uhu tabii sutaN. wakamunoo ?uNcu sooti ?NziraNdi sootaN. 「waNnee keera Ndoo」 Nci ?uNcoo sitataka kusamici ?iitaN
「cukutubaa kunu 'inaguNkai ?iirumadee joo」
?uNcoo macijanu tana doNdoN tatacaani 「?jaa ja waN ?uhu siQpai simitasi wakatoomi」
?uNcoo gaNcoonu tuukunu mii kirakira hwikaraci
* Page 12
?uhu ?abii sutaN
「waNnee ?ici turasuN ?jaa gutooru munoo
?waabagutu suru huri 'inagu Ndi ?iisa」
miQcaNoo hurahuraaQsi tanaNkai ?uQcakati
kataharaanu tiija mizitama mujoo nu ?iicunu burausuNkai ?atitaN.
waka ikigaa ?uNcuga erikubi kacimiti 「diQka ?ikana naa ?jariiru uQsaa ?icaeesani」 waka 'ikigaa kusamicooru iikaci hasirugucii kara hukaNkai hiQpati ?NjaN.
aNsikara mata muduticaani
「mitsusaN kunukutoo caasiN ?icoocusee masiNdi ?umaariisiga」 Ndi ?jutaN.
「nuuNci kuNgutooru muNdoo Nu QukuritagaNdi
?juru kutu ?anu 'ikigaa Buruumu baagaa Ndi ?juru keNcikunu seizu kacaa jaN waNniN ?aritu 'inutukuruNti citumitooN.
* Page 13
?aree kunu micici nu ?weeda mii SHIYAKUSHO nu SEKKEIZU kacuNdi nucikaziri jataN. keNshou miiati jataN aNsi cinuu joojaku zumenuNkai ?iNki ?iriiru tukuru madi subi naceetaN
?uNzuN wakairu tuui seizukacaaja caa enpitsuQsi sicagaci saani ?uriga subinainee ?atoo eNpitsu nu ?atu cucikami bikeeNnu hurupaNQsi kuususiga turigaru kesigomu jakaa juu kuusariiruBaatee」
「buruumu baagaa ja caa ?unupaN ?uNzunaa Nzi kootootaN.
jasiga cuu naa wakatoora hazijaa ?anu bataa joo
Qunutamini Buruumu baagaa nu zumeNoo cukee Nnakai
?osjaka nati neeraN naa caaNnaraNnati joo」
miQca Noo ?ukunu zaaNkai ?Nzi mizitama muyoo nu burausu haziti caa cicootaru mumeNnu huru joohukuNkai
* Page 14
cii keetaN ?urikara marumero nu miitu hoosha tunu maNkimuN hukanu ciribakuNkai sititaN.
?uwai
[記]
「沖縄語には語頭に促音 「つ」で始まる語があるとされている沖縄語辞典編纂 「時の誤りは排除した。又、城内の男性のみの言葉とされる発音 SZもこ こでは除外した。
* Page 15
1. この短編小説の和訳に「悪女のパン」 となっているのもあるが、 ここでは新潮文庫(大久保康雄訳) の 「賢女のパン」 を沖縄方言の発音 記号で「soo?iri 'winagu tu paN nu hanasi」 とした。
主人公ミス、マーサ、ミッチャムを 「みっちゃん」 即ちmiQcaNとした。
2. 口語では名詞の語尾を活用して助詞とする。(例外は殆どが文語のja) みっちゃんは⇔ miQcanoo、みっちゃんも⇔ miQcanuN etc
3. 独断と偏見で作った沖縄語の新語 [?irica nu hwica] 屋根裏。
本土の木造家屋には、物置や蚕部屋として使われる屋根裏部屋があるが、 沖縄の木造家屋にはそれが無い(台風の関係か傾斜が小さい)。言葉と しても辞書にも無い。木造家屋の合掌部分を言うイリチャがあるのみで ある。
そこで屋根裏部屋のことをイリチャヌフィチャ即ち ?irica nu hwica
とした。
